# config/config.yaml

env: "local"
grpc:
  port: 50001
  timeout: 10h
#postgres:
#  port: 5432
#  host: "localhost"
#  db_name: "customers"
#  user: "postgres"
#  password: "postgres"
#  sslmode: "false"