# config/docker_config.yaml

env: "local"
grpc:
  port: 50001
  timeout: 10h
http:
  port: 8080
postgres:
  port: 5432
  host: "localhost"
  db_name: "sso"
  user: "root"
  password: "root"
  sslmode: "disable"